### ISSUE TITLE
No memory metrics

### ISSUE THREAD

**Issue by rdesgrange-lf** [Ingensi/dockerbeat#117]
Hi,

I am using docker 1.11, I launched dockerbeat in a container from the hub. here is the dockerfile:
```
FROM ingensi/dockerbeat

COPY dockerbeat.yml /etc/dockerbeat/dockerbeat.yml
```
Here is my `dockerbeat.yml`:
```yaml
################### Dockerbeat Configuration Example #########################

############################# Dockerbeat ######################################

dockerbeat:
  # Defines how often a docker stat is sent to the output
  period: ${PERIOD:5}

  # Defines the docker socket path
  # By default, this will get the unix:///var/run/docker.sock
  socket: ${DOCKER_SOCKET:unix:///var/run/docker.sock}

  # If dockerbeat has to deal with a TLS-enabled docker daemon, you need to enable TLS and configure path for key and certificates.
  tls:
    # By default, TLS is disabled
    enable: ${DOCKER_ENABLE_TLS:false}

    # Path to the ca file
    ca_path: ${DOCKER_CA_PATH}

    # Path to the cert file
    cert_path: ${DOCKER_CERT_PATH}

    # Path to the key file
    key_path: ${DOCKER_KEY_PATH}
  stats:
    container: true
    net: true
    memory: true
    blkio: true
    cpu: true
###############################################################################
############################# Libbeat Config ##################################
# Base config file used by all other beats for using libbeat features

############################# Output ##########################################

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.
output:

  ### Elasticsearch as output
  elasticsearch:
    # Array of hosts to connect to.
    # Scheme and port can be left out and will be set to the default (http and 9200)
    # In case you specify and additional path, the scheme is required: http://localhost:9200/path
    # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
    hosts: ["myhost1:9200", "myhost2:9200"]

    index: "dockerbeat"






############################# Shipper #########################################

shipper:


############################# Logging #########################################

# There are three options for the log output: syslog, file, stderr.
# Under Windows systems, the log files are per default sent to the file output,
# under all other system per default to syslog.
logging:
  to_syslog: false
  to_files: true
  # To enable logging to files, to_files option has to be set to true
  files:
    # The directory where the log files will written to.
    path: /var/log/dockerbeat
    rotateeverybytes: 10485760 # = 10MB
  level: debug
```

And in elasticsearch I don't have any memory metrics, but I have the other one (cpu, container, blkio, net).

I tried with `latest` image and `develop` it doesn't work :-(
